### ISSUE TITLE
roadway data source

### ISSUE THREAD

**Issue by Wang4758** [tawheeler/NGSIM.jl#9]
Hello,
Could you please provide the data source where you got the roadway information (boundaries80.txt, boundaries101.txt, centerlines80.txt, centerlines101.txt)? I'm currently working on a project where we need the peachtree street data from NGSIM dataset to simulate intersaction driving. But I couldn't find the roadway coordinates on the NGSIM web.
Thank you very much

**Comment by tawheeler** [comment]
Those files I painstakingly constructed using the CAD files for 101 and 80. They do not exist for other NGSIM datasets.
